//===-- C65Subtarget.h - C65 subtarget information -------------*- C++ -*--===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// This file declares the C65 specific subclass of TargetSubtargetInfo.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_TARGET_C65SUBTARGET_H
#define LLVM_TARGET_C65SUBTARGET_H

//#include "llvm/ADT/Triple.h"
#include "llvm/Target/TargetSubtargetInfo.h"
#include <string>

#define GET_SUBTARGETINFO_HEADER
#include "C65GenSubtargetInfo.inc"

namespace llvm {
class StringRef;

class C65Subtarget : public C65GenSubtargetInfo {
  virtual void anchor();

private:
  Triple TargetTriple;

public:
  C65Subtarget(const std::string &TT, const std::string &CPU,
               const std::string &FS);

  // Automatically generated by tblgen.
  void ParseSubtargetFeatures(StringRef CPU, StringRef FS);
};
} // end namespace llvm

#endif
