//===-- C65Subtarget.h - C65 subtarget information -------------*- C++ -*--===//
//
//                     The LLVM Compiler Infrastructure
//
// This file is distributed under the University of Illinois Open Source
// License. See LICENSE.TXT for details.
//
//===----------------------------------------------------------------------===//
//
// This file declares the C65 specific subclass of TargetSubtargetInfo.
//
//===----------------------------------------------------------------------===//

#ifndef LLVM_TARGET_C65SUBTARGET_H
#define LLVM_TARGET_C65SUBTARGET_H

#include "C65FrameLowering.h"
#include "C65InstrInfo.h"
#include "C65ISelLowering.h"
#include "C65Subtarget.h"
#include "C65SelectionDAGInfo.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Target/TargetSubtargetInfo.h"
#include <string>

#define GET_SUBTARGETINFO_HEADER
#include "C65GenSubtargetInfo.inc"

namespace llvm {

class StringRef;

class C65Subtarget : public C65GenSubtargetInfo {
  virtual void anchor();
protected:
  bool InAcc8Mode;
  bool InAcc16Mode;
  bool InIx8Mode;
  bool InIx16Mode;
  bool Has65C02;
  bool Has65802;
  bool Has65816;
  void initializeSubtargetDependencies(StringRef CPU, StringRef FS);
private:
  Triple TargetTriple;
  C65InstrInfo InstrInfo;
  C65TargetLowering TLInfo;
  C65SelectionDAGInfo TSInfo;
  C65FrameLowering FrameLowering;

public:
  C65Subtarget(const std::string &TT, const std::string &CPU,
               const std::string &FS, TargetMachine &TM);

  const C65FrameLowering *getFrameLowering() const override {
    return &FrameLowering;
  }
  const C65InstrInfo *getInstrInfo() const override {
    return &InstrInfo;
  }
  const C65RegisterInfo *getRegisterInfo() const override {
    return &InstrInfo.getRegisterInfo();
  }
  const C65TargetLowering *getTargetLowering() const override {
    return &TLInfo;
  }
  const C65SelectionDAGInfo *getSelectionDAGInfo() const override {
    return &TSInfo;
  }

  // Automatically generated by tblgen.
  void ParseSubtargetFeatures(StringRef CPU, StringRef FS);

  // Return true if the target has 65C02 capabilities
  bool has65C02() const { return Has65C02; }

  // Return true if the target has 65802 capabilities
  bool has65802() const { return Has65802; }

  // Return true if the target has 65816 capabilities
  bool has65816() const { return Has65816; }

  // Return true if the accumulator register is currently 8-bit
  bool isAcc8Bit() const { return InAcc8Mode; }

  // Return true if the accumulator register is currently 16-bit
  bool isAcc16Bit() const { return InAcc16Mode; }

  // Return true if the index registers are currently 8-bit
  bool isIx8Bit() const { return InIx8Mode; }

  // Return true if the index registers are currently 16-bit
  bool isIx16Bit() const { return InIx16Mode; }
};
} // end namespace llvm

#endif
